//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       Entity_Gen.cst
//-- Date Generated: Monday, July 12, 2010
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Entity
{
    public partial class SYS_Staff
    {
		private int _OrganizationId;
		private int _UserId;
		private int _PositionId;
		private int _ID;
		private DateTime _FromDate;
		private DateTime _ToDate;
        private int _RoleID;
	
		public int OrganizationId { get{ return _OrganizationId; } set { _OrganizationId= value; } }
		public int UserId { get{ return _UserId; } set { _UserId= value; } }
		public int PositionId { get{ return _PositionId; } set { _PositionId= value; } }
		public int ID { get{ return _ID; } set { _ID= value; } }
		public DateTime FromDate { get{ return _FromDate; } set { _FromDate= value; } }
		public DateTime ToDate { get{ return _ToDate; } set { _ToDate= value; } }
        public int RoleID { get { return _RoleID; } set { _RoleID = value; } }
	
		public SYS_Staff(int OrganizationId, int UserId, int PositionId, int ID, DateTime FromDate, DateTime ToDate, int Role)
		{
			_OrganizationId = OrganizationId;
			_UserId = UserId;
			_PositionId = PositionId;
			_ID = ID;
			_FromDate = FromDate;
			_ToDate = ToDate;
		    _RoleID = Role;
		}
		public SYS_Staff()
		{
			_OrganizationId =  0;
			_UserId =  0;
			_PositionId =  0;
			_ID =  0;
			_FromDate =  DateTime.Now;
			_ToDate =  DateTime.Now;
		    _RoleID = 0;
		}
           
    }
}

