//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       Entity_Gen.cst
//-- Date Generated: Monday, July 12, 2010
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Entity
{
    public partial class SYS_RightOfUser
    {
		private int _RightId;
		private int _UserId;
		private Boolean _View;
		private Boolean _Update;
		private Boolean _Create;
		private Boolean _Delete;
		private Boolean _Approve;
		private int _ID;
	
		public int RightId { get{ return _RightId; } set { _RightId= value; } }
		public int UserId { get{ return _UserId; } set { _UserId= value; } }
		public Boolean View { get{ return _View; } set { _View= value; } }
		public Boolean Update { get{ return _Update; } set { _Update= value; } }
		public Boolean Create { get{ return _Create; } set { _Create= value; } }
		public Boolean Delete { get{ return _Delete; } set { _Delete= value; } }
		public Boolean Approve { get{ return _Approve; } set { _Approve= value; } }
		public int ID { get{ return _ID; } set { _ID= value; } }
	
		public SYS_RightOfUser(int RightId, int UserId, Boolean View, Boolean Update, Boolean Create, Boolean Delete, Boolean Approve, int ID)
		{
			_RightId = RightId;
			_UserId = UserId;
			_View = View;
			_Update = Update;
			_Create = Create;
			_Delete = Delete;
			_Approve = Approve;
			_ID = ID;
		}
		public SYS_RightOfUser()
		{
			_RightId =  0;
			_UserId =  0;
			_View =  false;
			_Update =  false;
			_Create =  false;
			_Delete =  false;
			_Approve =  false;
			_ID =  0;
		}
           
    }
}

