//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       Entity_Gen.cst
//-- Date Generated: Friday, May 20, 2011
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Entity
{
    public partial class SYS_Region
    {
        private int _ID;
        private string _Name;
        private string _Code;

        public int ID { get { return _ID; } set { _ID = value; } }
        public string Name { get { return _Name; } set { _Name = value; } }
        public string Code { get { return _Code; } set { _Code = value; } }

        public SYS_Region(int ID, string Name, string Code)
        {
            _ID = ID;
            _Name = Name;
            _Code = Code;
        }
        public SYS_Region()
        {
            _ID = 0;
            _Name = String.Empty;
            _Code = String.Empty;
        }

    }
}

