//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 6.0.0.0
//-- Template:       Entity_Gen.cst
//-- Date Generated: Wednesday, August 21, 2013
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Entity
{
    public partial class SYS_CCU
    {
        private int _ID;
        private DateTime _Time;
        private int _TotalRequest;
        private int _TotalOnline;
        private int _Online;

        public int ID { get { return _ID; } set { _ID = value; } }
        public DateTime Time { get { return _Time; } set { _Time = value; } }
        public int TotalRequest { get { return _TotalRequest; } set { _TotalRequest = value; } }
        public int TotalOnline { get { return _TotalOnline; } set { _TotalOnline = value; } }
        public int Online { get { return _Online; } set { _Online = value; } }

        public SYS_CCU(int ID, DateTime Time, int TotalRequest, int TotalOnline, int Online)
        {
            _ID = ID;
            _Time = Time;
            _TotalRequest = TotalRequest;
            _TotalOnline = TotalOnline;
            _Online = Online;
        }
        public SYS_CCU()
        {
            _ID = 0;
            _Time = DateTime.Now;
            _TotalRequest = 0;
            _TotalOnline = 0;
            _Online = 0;
        }

    }
}

