//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       Entity_Gen.cst
//-- Date Generated: Friday, May 20, 2011
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Entity
{
    public partial class SYS_Region_Organization
    {
        private int _ID;
        private int _IDRegion;
        private int _IDOrganization;

        public int ID { get { return _ID; } set { _ID = value; } }
        public int IDRegion { get { return _IDRegion; } set { _IDRegion = value; } }
        public int IDOrganization { get { return _IDOrganization; } set { _IDOrganization = value; } }

        public SYS_Region_Organization(int ID, int IDRegion, int IDOrganization)
        {
            _ID = ID;
            _IDRegion = IDRegion;
            _IDOrganization = IDOrganization;
        }
        public SYS_Region_Organization()
        {
            _ID = 0;
            _IDRegion = 0;
            _IDOrganization = 0;
        }

    }
}

