//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 4.0.0.0
//-- Template:       ServiceGen.cst
//-- Date Generated: Friday, September 19, 2014
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using Entity;
using System.ComponentModel;
namespace SystemManageService
{
	public partial class DM_MODULEService
    {
		private DM_MODULEDataAccess _dm_moduleDataAccess = new DM_MODULEDataAccess();
		
		public int InsertDM_MODULE(DM_MODULE dm_module)
        {
            return _dm_moduleDataAccess.InsertDM_MODULE(dm_module);
        }

        public int UpdateDM_MODULE(List<DM_MODULE> dm_modules)
        {
            return _dm_moduleDataAccess.UpdateDM_MODULE(dm_modules);
        }

        public void UpdateDM_MODULE(DM_MODULE dm_module)
        {
            _dm_moduleDataAccess.UpdateDM_MODULE(dm_module);
        }

        public void DeleteDM_MODULE(List<DM_MODULE> dm_modules)
        {
            _dm_moduleDataAccess.DeleteDM_MODULE(dm_modules);
        }

        public void DeleteDM_MODULE(DM_MODULE dm_modules)
        {
            _dm_moduleDataAccess.DeleteDM_MODULE(dm_modules);
        }

        public DM_MODULE SelectDM_MODULE(int dm_moduleId)
        {
            return _dm_moduleDataAccess.SelectDM_MODULE(dm_moduleId);
        }

        public List<DM_MODULE> SelectAllDM_MODULE()
        {
            return _dm_moduleDataAccess.SelectAllDM_MODULE();
        }
		
		public BindingList<DM_MODULE> SelectBindingAllDM_MODULE()
        {
            return _dm_moduleDataAccess.SelectBindingAllDM_MODULE();
        }
	 	
	 	
	}
}



