//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiQL_SangLoc
{


    public partial class ImportData
    {

        /// <summary>
        /// txt11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label txt11;

        /// <summary>
        /// fileUp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FileUpload fileUp;

        /// <summary>
        /// hdTenFile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdTenFile;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
        /// <summary>
        /// btnXem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton btnXem;
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// btnConvert control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxButton btnConvert;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// ASPxLabel4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel ASPxLabel4;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// txtDienAp control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxTextBox txtDienAp;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// ASPxLabel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel ASPxLabel1;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// txtMaTram control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxTextBox txtMaTram;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// ASPxLabel2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel ASPxLabel2;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// txtHSCS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxTextBox txtHSCS;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// ASPxLabel3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel ASPxLabel3;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// lbTonThatKyThat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxLabel lbTonThatKyThat;
<<<<<<< Updated upstream

=======
<<<<<<< HEAD
        
=======

>>>>>>> Congtt
>>>>>>> Stashed changes
        /// <summary>
        /// grvView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DevExpress.Web.ASPxGridView grvView;
    }
}
