//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       DataAcessGen.cst
//-- Date Generated: Monday, July 12, 2010
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Text;
using Connection;
using Entity;


namespace DataAccess
{
    public partial class SYS_RoleOfUserDataAccess
    {

        private SYS_RoleOfUser _sys_roleofuser;

        private MSSqlHelper _DbHelper = new MSSqlHelper();

        public static string FIELD_USERID = "UserId";
        public static string FIELD_ROLEID = "RoleId";
        public static string FIELD_ID = "ID";


        #region Private methods

        private static void SetSYS_RoleOfUserInfo(DbDataReader reader, ref SYS_RoleOfUser sys_roleofuser)
        {
            sys_roleofuser.UserId = int.Parse("0" + reader[FIELD_USERID]);
            sys_roleofuser.RoleId = int.Parse("0" + reader[FIELD_ROLEID]);
            sys_roleofuser.ID = int.Parse("0" + reader[FIELD_ID]);
        }

        private static void SetListSYS_RoleOfUserInfo(ref DbDataReader reader, ref List<SYS_RoleOfUser> sys_roleofusers)
        {
            SYS_RoleOfUser sys_roleofuser = null;
            while (reader.Read())
            {
                sys_roleofuser = new SYS_RoleOfUser();
                SYS_RoleOfUserDataAccess.SetSYS_RoleOfUserInfo(reader, ref sys_roleofuser);
                sys_roleofusers.Add(sys_roleofuser);
            }
        }

        #endregion

        #region Static methods
        #endregion
        public int InsertSYS_RoleOfUser(SYS_RoleOfUser sys_roleofuser)
        {
            DbConnection conn = _DbHelper.CreateConnection(Common.ConnectionString);
            conn.Open();
            try
            {
                List<DbParameter> para = new List<DbParameter>();
                para.Add(_DbHelper.CreateParameter(FIELD_USERID, sys_roleofuser.UserId, false));
                para.Add(_DbHelper.CreateParameter(FIELD_ROLEID, sys_roleofuser.RoleId, false));
                DbParameter ouput = _DbHelper.CreateParameter(FIELD_ID, DbType.Int32, true);
                para.Add(ouput);
                _DbHelper.ExecuteReader(conn, Common.DatabaseSchema + "[SYS_RoleOfUser_Insert]", para.ToArray());
                return (int)ouput.Value;
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.Insert: {0}", ex.Message));
            }
            finally
            {
                conn.Close();
            }
        }

        public int UpdateSYS_RoleOfUser(List<SYS_RoleOfUser> sys_roleofusers)
        {
            DbConnection conn = _DbHelper.CreateConnection(Common.ConnectionString);
            conn.Open();
            int count = 0;
            try
            {

                foreach (SYS_RoleOfUser sys_roleofuser in sys_roleofusers)
                {
                    List<DbParameter> para = new List<DbParameter>();

                    para.Add(_DbHelper.CreateParameter(FIELD_USERID, sys_roleofuser.UserId, false));
                    para.Add(_DbHelper.CreateParameter(FIELD_ROLEID, sys_roleofuser.RoleId, false));
                    para.Add(_DbHelper.CreateParameter(FIELD_ID, sys_roleofuser.ID, false));

                    _DbHelper.ExecuteNonQuery(conn, Common.DatabaseSchema + "[sys_roleofuser_Update]", para.ToArray());
                    count++;
                }
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.Update: {0}", ex.Message));
            }
            finally
            {
                conn.Close();
            }
            return count;
        }

        public void UpdateSYS_RoleOfUser(SYS_RoleOfUser sys_roleofuser)
        {
            DbConnection conn = _DbHelper.CreateConnection(Common.ConnectionString);
            conn.Open();
            try
            {
                List<DbParameter> para = new List<DbParameter>();

                para.Add(_DbHelper.CreateParameter(FIELD_USERID, sys_roleofuser.UserId, false));
                para.Add(_DbHelper.CreateParameter(FIELD_ROLEID, sys_roleofuser.RoleId, false));
                para.Add(_DbHelper.CreateParameter(FIELD_ID, sys_roleofuser.ID, false));

                _DbHelper.ExecuteReader(conn, Common.DatabaseSchema + "[SYS_RoleOfUser_Update]", para.ToArray());

            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.Update: {0}", ex.Message));
            }
            finally
            { conn.Close(); }
        }

        public void DeleteSYS_RoleOfUser(List<SYS_RoleOfUser> sys_roleofusers)
        {
            DbConnection conn = _DbHelper.CreateConnection(Common.ConnectionString);
            conn.Open();
            List<DbParameter> para = new List<DbParameter>();

            try
            {

                foreach (SYS_RoleOfUser sys_roleofuser in sys_roleofusers)
                {

                    para.Add(_DbHelper.CreateParameter(FIELD_ID, sys_roleofuser.ID, false));

                    _DbHelper.ExecuteNonQuery(conn, Common.DatabaseSchema + "[SYS_RoleOfUser_Delete]", para.ToArray());
                    para.Clear();
                }
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.Delete: {0}", ex.Message));
            }
            finally
            {
                conn.Close();
            }
        }

        public void DeleteSYS_RoleOfUser(SYS_RoleOfUser sys_roleofuser)
        {
            DbConnection conn = _DbHelper.CreateConnection(Common.ConnectionString);
            conn.Open();
            try
            {
                List<DbParameter> para = new List<DbParameter>();
                para.Add(_DbHelper.CreateParameter(FIELD_ID, sys_roleofuser.ID, false));
                _DbHelper.ExecuteReader(conn, Common.DatabaseSchema + "[SYS_RoleOfUser_Delete]", para.ToArray());
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                conn.Close();
            }

        }

        public SYS_RoleOfUser SelectSYS_RoleOfUser(int ID)
        {
            DbConnection conn = _DbHelper.CreateConnection(Common.ConnectionString);
            conn.Open();
            SYS_RoleOfUser sys_roleofuser = new SYS_RoleOfUser();
            DbDataReader reader = null;
            try
            {
                List<DbParameter> para = new List<DbParameter>();
                para.Add(_DbHelper.CreateParameter(FIELD_ID, ID, false));

                reader = _DbHelper.ExecuteReader(conn, Common.DatabaseSchema + "[SYS_RoleOfUser_SelectById]", para.ToArray());
                if (reader.HasRows && reader.Read())
                    SYS_RoleOfUserDataAccess.SetSYS_RoleOfUserInfo(reader, ref sys_roleofuser);
                return sys_roleofuser;
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.SelectById: {0}", ex.Message));
            }
            finally
            {
                if (reader != null)
                    reader.Close();
                conn.Close();
            }

        }


        public List<SYS_RoleOfUser> SelectAllSYS_RoleOfUser()
        {
            DbConnection conn = _DbHelper.CreateConnection(Common.ConnectionString);
            conn.Open();
            List<SYS_RoleOfUser> sys_roleofuser = new List<SYS_RoleOfUser>();
            DbDataReader reader = null;
            try
            {
                reader = _DbHelper.ExecuteReader(conn, Common.DatabaseSchema + "[SYS_RoleOfUser_SelectAll]", (DbParameter[])null);
                if (reader.HasRows)
                    SYS_RoleOfUserDataAccess.SetListSYS_RoleOfUserInfo(ref reader, ref sys_roleofuser);
                return sys_roleofuser;
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format(" SYS_RoleOfUserDataAccess.SelectAll: {0}", ex.Message));
            }
            finally
            {
                if (reader != null)
                    reader.Close();
                conn.Close();
            }
        }

        public int InsertSYS_RoleOfUser(DbTransaction transaction, SYS_RoleOfUser sys_roleofuser)
        {
            try
            {
                List<DbParameter> para = new List<DbParameter>();

                para.Add(_DbHelper.CreateParameter(FIELD_USERID, sys_roleofuser.UserId, false));
                para.Add(_DbHelper.CreateParameter(FIELD_ROLEID, sys_roleofuser.RoleId, false));
                DbParameter ouput = _DbHelper.CreateParameter(FIELD_ID, DbType.Int32, true);

                para.Add(ouput);

                _DbHelper.ExecuteNonQuery(transaction, Common.DatabaseSchema + "[SYS_RoleOfUser_Insert]", para.ToArray());

                return (int)ouput.Value;
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.Insert: {0}", ex.Message));
            }
        }



        public int UpdateSYS_RoleOfUser(DbTransaction transaction, List<SYS_RoleOfUser> sys_roleofusers)
        {

            int count = 0;
            try
            {

                foreach (SYS_RoleOfUser sys_roleofuser in sys_roleofusers)
                {
                    List<DbParameter> para = new List<DbParameter>();

                    para.Add(_DbHelper.CreateParameter(FIELD_USERID, sys_roleofuser.UserId, false));
                    para.Add(_DbHelper.CreateParameter(FIELD_ROLEID, sys_roleofuser.RoleId, false));
                    para.Add(_DbHelper.CreateParameter(FIELD_ID, sys_roleofuser.ID, false));

                    _DbHelper.ExecuteNonQuery(transaction, Common.DatabaseSchema + "[SYS_RoleOfUser_Update]", para.ToArray());
                    count++;
                }
            }

            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.Update: {0}", ex.Message));
            }

            return count;
        }

        public void UpdateSYS_RoleOfUser(DbTransaction transaction, SYS_RoleOfUser sys_roleofuser)
        {
            try
            {
                List<DbParameter> para = new List<DbParameter>();

                para.Add(_DbHelper.CreateParameter(FIELD_USERID, sys_roleofuser.UserId, false));
                para.Add(_DbHelper.CreateParameter(FIELD_ROLEID, sys_roleofuser.RoleId, false));
                para.Add(_DbHelper.CreateParameter(FIELD_ID, sys_roleofuser.ID, false));

                _DbHelper.ExecuteNonQuery(transaction, Common.DatabaseSchema + "[SYS_RoleOfUser_Update]", para.ToArray());

            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.Update: {0}", ex.Message));
            }
        }

        public int DeleteSYS_RoleOfUser(DbTransaction transaction, List<SYS_RoleOfUser> sys_roleofusers)
        {
            int count = 0;
            try
            {
                List<DbParameter> para = new List<DbParameter>();
                foreach (SYS_RoleOfUser sys_roleofuser in sys_roleofusers)
                {
                    para.Add(_DbHelper.CreateParameter(FIELD_ID, DbType.Int32, false));

                    _DbHelper.ExecuteNonQuery(transaction, Common.DatabaseSchema + "[SYS_RoleOfUser_Delete]", para.ToArray());
                    para.Clear();
                    count++;
                }
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_RoleOfUserDataAccess.Delete: {0}", ex.Message));
            }

            return count;
        }
    }
}

