//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       DataAcess.cst
//-- Date Generated: Monday, July 05, 2010
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Text;
using Entity;

namespace DataAccess
{
    public partial class SYS_PositionDataAccess
    {

        public List<SYS_Position> SYS_Position_GetByIDSYS_OrganizationPositionRole(int OrganizationId)
        {
            DbConnection conn = _DbHelper.CreateConnection(Common.ConnectionString);
            conn.Open();
            List<SYS_Position> sys_position = new List<SYS_Position>();
            DbDataReader reader = null;
            try
            {
                List<DbParameter> para = new List<DbParameter>();
                para.Add(_DbHelper.CreateParameter(FIELD_ID, OrganizationId, false));

                reader = _DbHelper.ExecuteReader(conn, Common.DatabaseSchema + "[SYS_Position_GetByIDSYS_OrganizationPositionRole]", para.ToArray());
                if (reader.HasRows)
                    SYS_PositionDataAccess.SetListSYS_PositionInfo(ref reader, ref sys_position);
                return sys_position;
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_Position_GetByIDSYS_OrganizationPositionRole.SelectById: {0}", ex.Message));
            }
            finally
            {
                if (reader != null)
                    reader.Close();
                conn.Close();
            }

        }

        public SYS_Position SelectSYS_Position(DbConnection conn,int ID)
        {

            SYS_Position sys_position = new SYS_Position();
            DbDataReader reader = null;
            try
            {
                if (conn.State == ConnectionState.Closed)
                {
                    conn.Open();
                }
                else
                {
                    if (conn.State!=ConnectionState.Open)
                    {
                        throw new Exception("Connection is not ready");    
                    }
                    
                }
                List<DbParameter> para = new List<DbParameter>();
                para.Add(_DbHelper.CreateParameter(FIELD_ID, ID, false));

                reader = _DbHelper.ExecuteReader(conn, Common.DatabaseSchema + "[SYS_Position_GetByID]", para.ToArray());
                if (reader.HasRows && reader.Read())
                    SYS_PositionDataAccess.SetSYS_PositionInfo(reader, ref sys_position);
                return sys_position;
            }
            catch (Exception ex)
            {
                throw new Exception(String.Format("SYS_PositionDataAccess.SelectById: {0}", ex.Message));
            }
            finally
            {
                if (reader != null)
                    reader.Close();
            }

        }
    }
}


