//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       ServiceGen.cst
//-- Date Generated: Friday, October 28, 2011
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using Entity;
namespace SystemManageService
{
    public partial class SYS_ColumnCategoryService 
    {
        private SYS_ColumnCategoryDataAccess _sys_columncategoryDataAccess = new SYS_ColumnCategoryDataAccess();

        public int InsertSYS_ColumnCategory(SYS_ColumnCategory sys_columncategory)
        {
            return _sys_columncategoryDataAccess.InsertSYS_ColumnCategory(sys_columncategory);
        }

        public int UpdateSYS_ColumnCategory(List<SYS_ColumnCategory> sys_columncategorys)
        {
            return _sys_columncategoryDataAccess.UpdateSYS_ColumnCategory(sys_columncategorys);
        }

        public void UpdateSYS_ColumnCategory(SYS_ColumnCategory sys_columncategory)
        {
            _sys_columncategoryDataAccess.UpdateSYS_ColumnCategory(sys_columncategory);

        }

        public void DeleteSYS_ColumnCategory(List<SYS_ColumnCategory> sys_columncategorys)
        {
            _sys_columncategoryDataAccess.DeleteSYS_ColumnCategory(sys_columncategorys);
        }

        public void DeleteSYS_ColumnCategory(SYS_ColumnCategory sys_columncategorys)
        {
            _sys_columncategoryDataAccess.DeleteSYS_ColumnCategory(sys_columncategorys);
        }

        public SYS_ColumnCategory SelectSYS_ColumnCategory(int sys_columncategoryId)
        {
            return _sys_columncategoryDataAccess.SelectSYS_ColumnCategory(sys_columncategoryId);
        }

        public List<SYS_ColumnCategory> SelectAllSYS_ColumnCategory()
        {
            return _sys_columncategoryDataAccess.SelectAllSYS_ColumnCategory();
        }
        public List<SYS_ColumnCategory> SelectAllSYS_ColumnCategoryByTable(string Table)
        {
            return _sys_columncategoryDataAccess.SelectAllSYS_ColumnCategoryByNameTable(Table);
        }

        public List<SYS_ColumnCategory> SelectAllSYS_ColumnCategoryByIDCatManager(int IDCatManager)
        {
            return _sys_columncategoryDataAccess.SelectAllSYS_ColumnCategoryByIDCatManager(IDCatManager);
        }
    }
}



