//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 6.0.0.0
//-- Template:       ServiceGen.cst
//-- Date Generated: Wednesday, August 21, 2013
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using Entity;
using System.ComponentModel;
namespace SystemManageService
{
    public partial class SYS_CCUService
    {
        public List<SYS_CCU> SelectAllSYS_CCU_ByDateTime(DateTime dtime, int TuGio, int DenGio)
        {
            DateTime Tu = new DateTime(dtime.Year, dtime.Month, dtime.Day, TuGio, 0, 0);
            DateTime Den = new DateTime(dtime.Year, dtime.Month, dtime.Day, DenGio, 59, 0);            
            return _sys_ccuDataAccess.SelectAllSYS_CCU_ByDateTime(Tu,Den);
        }     

    }
}



