//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       ServiceGen.cst
//-- Date Generated: Monday, July 12, 2010
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using Entity;
namespace SystemManageService
{
	public partial class SYS_UserService
    {
		private SYS_UserDataAccess _sys_userDataAccess = new SYS_UserDataAccess();
		
		public int InsertSYS_User(SYS_User sys_user)
        {
            return _sys_userDataAccess.InsertSYS_User(sys_user);
        }

        public int UpdateSYS_User(List<SYS_User> sys_users)
        {
            return _sys_userDataAccess.UpdateSYS_User(sys_users);
        }

        public void UpdateSYS_User(SYS_User sys_user)
        {
            _sys_userDataAccess.UpdateSYS_User(sys_user);
        }
        public void UpdateSYS_UserPassWord(int ID, string Password)
        {
            _sys_userDataAccess.UpdateSYS_UserPassWord(ID, Password);
        }
        public void DeleteSYS_User(List<SYS_User> sys_users)
        {
            _sys_userDataAccess.DeleteSYS_User(sys_users);
        }

        public void DeleteSYS_User(SYS_User sys_users)
        {
            _sys_userDataAccess.DeleteSYS_User(sys_users);
        }

        public SYS_User SelectSYS_User(int sys_userId)
        {
            return _sys_userDataAccess.SelectSYS_User(sys_userId);
        }

        public List<SYS_User> SelectAllSYS_User()
        {
            return _sys_userDataAccess.SelectAllSYS_User();
        }
       
	}
}



