//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       ServiceGen.cst
//-- Date Generated: Monday, September 26, 2011
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using Entity;
namespace SystemManageService
{
    public partial class SYS_ProvinceService 
    {
        private SYS_ProvinceDataAccess _sys_provinceDataAccess = new SYS_ProvinceDataAccess();

        public int InsertSYS_Province(SYS_Province sys_province)
        {
            return _sys_provinceDataAccess.InsertSYS_Province(sys_province);
        }

        public int UpdateSYS_Province(List<SYS_Province> sys_provinces)
        {
            return _sys_provinceDataAccess.UpdateSYS_Province(sys_provinces);
        }

        public void UpdateSYS_Province(SYS_Province sys_province)
        {
            _sys_provinceDataAccess.UpdateSYS_Province(sys_province);
        }

        public void DeleteSYS_Province(List<SYS_Province> sys_provinces)
        {
            _sys_provinceDataAccess.DeleteSYS_Province(sys_provinces);
        }

        public void DeleteSYS_Province(SYS_Province sys_provinces)
        {
            _sys_provinceDataAccess.DeleteSYS_Province(sys_provinces);
        }

        public SYS_Province SelectSYS_Province(int sys_provinceId)
        {
            return _sys_provinceDataAccess.SelectSYS_Province(sys_provinceId);
        }

        public List<SYS_Province> SelectAllSYS_Province()
        {
            return _sys_provinceDataAccess.SelectAllSYS_Province();
        }

    }
}



