//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       ServiceGen.cst
//-- Date Generated: Monday, July 12, 2010
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using Entity;
namespace SystemManageService
{
	public partial class SYS_StaffService
    {
	    private SYS_StaffDataAccess _sys_staffDataAccess = new SYS_StaffDataAccess();
		




        public void DeleteSYS_Staff(List<SYS_Staff> sys_staffs)
        {
            _sys_staffDataAccess.DeleteSYS_Staff(sys_staffs);
        }

        public void DeleteSYS_Staff(SYS_Staff sys_staffs)
        {
            _sys_staffDataAccess.DeleteSYS_Staff(sys_staffs);
        }

        public SYS_Staff SelectSYS_Staff(int sys_staffId)
        {
            return _sys_staffDataAccess.SelectSYS_Staff(sys_staffId);
        }

        public List<SYS_Staff> SelectAllSYS_Staff()
        {
            return _sys_staffDataAccess.SelectAllSYS_Staff();
        }
	 	
	}
}



