//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       ServiceGen.cst
//-- Date Generated: Monday, July 12, 2010
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using Entity;
namespace SystemManageService
{
	public partial class SYS_PositionService
    {
		private SYS_PositionDataAccess _sys_positionDataAccess = new SYS_PositionDataAccess();
		
		public int InsertSYS_Position(SYS_Position sys_position)
        {
            return _sys_positionDataAccess.InsertSYS_Position(sys_position);
        }
       
        public int UpdateSYS_Position(List<SYS_Position> sys_positions)
        {
            return _sys_positionDataAccess.UpdateSYS_Position(sys_positions);
        }

        public void UpdateSYS_Position(SYS_Position sys_position)
        {
            _sys_positionDataAccess.UpdateSYS_Position(sys_position);
        }

        public void DeleteSYS_Position(List<SYS_Position> sys_positions)
        {
            _sys_positionDataAccess.DeleteSYS_Position(sys_positions);
        }

        public void DeleteSYS_Position(SYS_Position sys_positions)
        {
            _sys_positionDataAccess.DeleteSYS_Position(sys_positions);
        }

        public SYS_Position SelectSYS_Position(int sys_positionId)
        {
            return _sys_positionDataAccess.SelectSYS_Position(sys_positionId);
        }

        public List<SYS_Position> SelectAllSYS_Position()
        {
            return _sys_positionDataAccess.SelectAllSYS_Position();
        }
	 	
	}
}



