//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 5.0.0.0
//-- Template:       Service.cst
//-- Date Generated: Monday, July 12, 2010
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Entity;

namespace SystemManageService
{
    public partial class SYS_RightOfUserService
    {
        public int InsertSYS_RightOfUser(List<SYS_RightOfUser> sys_rightofuser)
        {
            return _sys_rightofuserDataAccess.InsertSYS_RightOfUser(sys_rightofuser);
        }

        public void DeleteSYS_RightOfUserByIDUser(SYS_RightOfUser sys_rightofusers)
        {
            _sys_rightofuserDataAccess.DeleteSYS_RightOfUserByIDUser(sys_rightofusers);
        }
    }
}


