//------------------------------------------------------------------------------------------------------------------------
//-- Generated By:   TrungVK using CodeSmith 4.0.0.0
//-- Template:       ServiceGen.cst
//-- Date Generated: Thursday, January 17, 2013
//------------------------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess;
using Entity;
using System.ComponentModel;
namespace SystemManageService
{
	public partial class SYS_LogService
    {
		private SYS_LogDataAccess _sys_logDataAccess = new SYS_LogDataAccess();
		
		public int InsertSYS_Log(SYS_Log sys_log)
        {
            return _sys_logDataAccess.InsertSYS_Log(sys_log);
        }

        public int UpdateSYS_Log(List<SYS_Log> sys_logs)
        {
            return _sys_logDataAccess.UpdateSYS_Log(sys_logs);
        }

        public void UpdateSYS_Log(SYS_Log sys_log)
        {
            _sys_logDataAccess.UpdateSYS_Log(sys_log);
        }

        public void DeleteSYS_Log(List<SYS_Log> sys_logs)
        {
            _sys_logDataAccess.DeleteSYS_Log(sys_logs);
        }

        public void DeleteSYS_Log(SYS_Log sys_logs)
        {
            _sys_logDataAccess.DeleteSYS_Log(sys_logs);
        }

        public SYS_Log SelectSYS_Log(int sys_logId)
        {
            return _sys_logDataAccess.SelectSYS_Log(sys_logId);
        }

        public List<SYS_Log> SelectAllSYS_Log()
        {
            return _sys_logDataAccess.SelectAllSYS_Log();
        }
        public SYS_Log SelectAllSYS_Log_ByActionAndIDBC(int IDBC,int Action)
        {
            return _sys_logDataAccess.SelectAllSYS_Log_ByActionAndIDBC(IDBC, Action);
        }
		
		public BindingList<SYS_Log> SelectBindingAllSYS_Log()
        {
            return _sys_logDataAccess.SelectBindingAllSYS_Log();
        }
	 	
	 	
	}
}



